
### Send POST request with json body
POST http://localhost:3000/bureau
Content-Type: application/json

{
  "id_responsable": "64466cb490f5aedd902b8da4",
  "id_chef_section": "64466cb490f5aedd902b8da4",
  "localisation": "IUT",
  "description": "boo test",
  "ville": "Bandjoun",
  "nom": "bureau de l'IUT",
  "password": "644425265de51896be5bfd7a",
  "id_section": "64466920fb9ae44dc640f89b",
  "id_election": "64466a49fb9ae44dc640f8ab"

}

### Send POST request with json body
POST http://localhost:3000/bureau
Content-Type: application/json

{
  "id_responsable": "6444c7e0c2bb050dd7fef222",
  "id_chef_section": "6444c887c2bb050dd7fef225",
  "localisation": "ecole primaire",
  "description": "boo test",
  "ville": "Bandjoun",
  "nom": "bureau de l'ecole primaire",
  "password": "12345678",
  "id_section": "6444ba66bf96f176015d8045",
  "id_election": "644425265de51896be5bfd7a"

}

### Send POST request with json body
PUT http://localhost:3000/bureau
Content-Type: application/json

{
  "id_responsable": "6444c7e0c2bb050dd7fef222",
  "id_chef_section": "6444c887c2bb050dd7fef225",
  "localisation": "IUT",
  "description": "",
  "ville": "Bandjoun",
  "nom": "bureau de l'IUT",
  "password": "644425265de51896be5bfd7a",
  "id_section": "6444ba66bf96f176015d8045",
  "id_election": "644425265de51896be5bfd7a",
  "_id": "644547707398b1e1b3b86ff7"

}

### Send POST request with json body
PUT http://localhost:3000/bureau
Content-Type: application/json

{
  "code": "poiuiop",
  "id_organisation": "644425265de51896be5bfd7a",
  "libele": "delege de CDRI",
  "_id": "6444aa0fe6a97f9bc6dd05c6",
  "__v": 0
}

### Send POST request with json body
POST http://localhost:3000/election
Content-Type: application/json

{
  "_id": "644425265de51896be5bfd7a",
  "code": "verudy",
  "nom": "ElECAM",
  "id_user": 14
}

### Send POST request with json body
PUT http://localhost:3000/election
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWNrdGV1ZGVtIiwic3ViIjozLCJpYXQiOjE2ODExMzY1NTcsImV4cCI6MTY4MTEzNjY3N30.i6AGZ7EnD7_2aIX7tZIkdttVs8VW4W9z3_R15EkfB_4

{
  "id": 3,
  "login": "erickteudem",
  "nom": "Nteudem",
  "prenom": "Erick",
  "numero": "654190514",
  "password": "101156204",
  "date_naissance": "2001-01-04",
  "image": "popopop"

}


### Send GET request
DELETE http://localhost:3000/bureau/644542950d80b6e4db7de2b1
Accept: application/json

### Send GET request
GET http://localhost:3000/election
Accept: application/json

### Send GET request
GET http://localhost:3000/bureau/all
Accept: application/json

### Send POST request with json body
GET http://localhost:3000/election/organisation/644425265de51896be5bfd7a
Accept: application/json

### Send GET request with json body
GET http://localhost:3000/bureau/644547707398b1e1b3b86ff7
Accept: application/json
